name: pancakes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  youtube_player_flutter: ^9.1.1
  
  http: ^1.1.0
  
  json_annotation: ^4.8.1
  
  go_router: ^12.1.3
  
  url_launcher: ^6.3.2
  
  curved_navigation_bar: ^1.0.3
  
  share_plus: ^7.2.1
  
  provider: ^6.1.1
  
  google_maps_flutter: ^2.5.3
  
  shared_preferences: ^2.2.2
  
  image_picker: ^1.0.5
  webview_flutter_wkwebview: ^3.22.1
  dio: ^5.8.0+1
  webview_flutter: ^4.13.0
  battery_plus: ^6.0.0
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Gabarito
      fonts:
        - asset: assets/fonts/Gabarito-Regular.ttf
